ENV: local
Name: restful-file-zip
Host: localhost
Port: 8081
SourcePath: tmp/source
UndoFolderName: undo
ArchivePath: tmp/archive
Cors:
  AllowAllOrigins: false
  AllowOrigins: [http://localhost:8080]
  AllowMethods: [GET, POST, PUT, DELETE]
  AllowHeaders: [content-type]
  ExposeHeaders: []
  AllowCredentials: false
